version: "3.7"

services:
  app:
    build: .
    container_name: crop-api
    environment:
      - "DATABASE_URL=${DATABASE_URL}"

    restart: always
    volumes:
      - .:/usr/src/app

    ports:
      - "5001:5001"
